classDiagram
%%    Associations - A relationship in which at least one entity holds a reference to the other
%%    but there is no owner and they can exist independently.
    Title -- Genre
%%    Composite Relationships - There's an owner of the relationship, and children will be
%%    deleted if the parent is. Solid diamond indicates the 'parent'.
    Title *-- Season
    Title *-- Review
%%    Aggregate Relationship - There's an owner of the relationship, but they can exist
%%    independently of one another. 'Actor' can exist if 'Title' is deleted.
    Title o-- Actor

    Season *-- Episode